# Generated by Django 2.2.10 on 2021-03-02 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('TXT', 'Ответ текстом'), ('ONE', 'Выбор одного правильного варианта'), ('MANY', 'Выбор нескольких правильных вариантов')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('text', models.TextField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls_app.QuestionModel')),
            ],
        ),
        migrations.CreateModel(
            name='PollModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_start', models.DateField(editable=False)),
                ('date_end', models.DateField()),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls_app.QuestionModel')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nickname', models.CharField(max_length=25, unique=True)),
                ('anon_id', models.IntegerField(default=None, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('polls', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls_app.PollModel')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
                ('answers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls_app.AnswerModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
