# Generated by Django 2.2.10 on 2021-03-02 15:03

from django.db import migrations
import polls_app.user_manager


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0002_auto_20210302_1757'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
                ('objects', polls_app.user_manager.CustomUserManager()),
            ],
        ),
    ]
