# Generated by Django 2.2.10 on 2021-03-02 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0003_auto_20210302_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='nickname',
            new_name='username',
        ),
    ]
