# Generated by Django 2.2.10 on 2021-03-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0008_auto_20210302_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollmodel',
            name='questions',
        ),
        migrations.AddField(
            model_name='pollmodel',
            name='questions',
            field=models.ManyToManyField(blank=True, to='polls_app.QuestionModel'),
        ),
    ]
