# Generated by Django 2.2.10 on 2021-03-02 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0009_auto_20210302_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='answermodel',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answermodel',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls_app.QuestionModel'),
        ),
    ]
