# Generated by Django 2.2.10 on 2021-03-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0010_auto_20210303_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='answers',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='answers',
            field=models.ManyToManyField(blank=True, to='polls_app.AnswerModel'),
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='polls',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='polls',
            field=models.ManyToManyField(blank=True, to='polls_app.PollModel'),
        ),
    ]
